Adding ClangTidyReview

diff --git a/.github/workflows/validity_check_pr.yml b/.github/workflows/validity_check_pr.yml
--- a/.github/workflows/validity_check_pr.yml
+++ b/.github/workflows/validity_check_pr.yml
@@ -133,3 +133,21 @@ jobs:
         doxyfile-path: .github/github_doxy #Errors on warnings
     - name: Check for successful doc
       run: "test -f out/documents/html/index.html && echo 'we good' || exit 1"
+      
+  ClangTidyReview:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+
+    # Optionally generate compile_commands.json
+
+    - uses: ZedThree/clang-tidy-review@v0.12.0
+      id: review
+
+    # Uploads an artefact containing clang_fixes.json
+    - uses: ZedThree/clang-tidy-review/upload@v0.12.0
+      id: upload-review
+
+    # If there are any comments, fail the check
+    - if: steps.review.outputs.total_comments > 0
+      run: exit 1
